// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcn7J7oyvgdRiG2qIK-fqmJkT4wMZIDxQ',
    appId: '1:57427886443:web:1a4b2de5f9735062ac4c2e',
    messagingSenderId: '57427886443',
    projectId: 'groupie-71b28',
    authDomain: 'groupie-71b28.firebaseapp.com',
    storageBucket: 'groupie-71b28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLJlpIyixX_b3jjwi73yGX6r8TjhcxNsc',
    appId: '1:57427886443:android:e2a680f8e7022a75ac4c2e',
    messagingSenderId: '57427886443',
    projectId: 'groupie-71b28',
    storageBucket: 'groupie-71b28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpxHSkkBiEidYINf521epBeOp7f2w5SAM',
    appId: '1:57427886443:ios:06336efaec15450bac4c2e',
    messagingSenderId: '57427886443',
    projectId: 'groupie-71b28',
    storageBucket: 'groupie-71b28.appspot.com',
    iosClientId:
        '57427886443-bsle7hbdvlv2k2s3neudf8ndhpbqid4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpxHSkkBiEidYINf521epBeOp7f2w5SAM',
    appId: '1:57427886443:ios:93d83810a2b4874eac4c2e',
    messagingSenderId: '57427886443',
    projectId: 'groupie-71b28',
    storageBucket: 'groupie-71b28.appspot.com',
    iosClientId:
        '57427886443-aupahs5cvqs467otrnq0qugt3u1sfhsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupie.RunnerTests',
  );
}
